name: Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
      - gh-pages  # Added this to handle pushes to gh-pages
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Add explicit permissions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all branches

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-rtd-theme

    - name: Create .nojekyll file
      run: |
        touch .nojekyll

    - name: Build documentation
      run: |
        sphinx-build -b html source/ build/html

    - name: Deploy to GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/html
        force_orphan: true
        publish_branch: gh-pages
        enable_jekyll: false
